### ISSUE TITLE
assert()s in composite kernel and user-level

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#161]
assert()s in composite are not working at present in most places except for platform/i386/kernel.c and platform/i386/boot_comp.c. 

I've saved my work here : https://github.com/phanikishoreg/Composite/commit/9f4753a607bcd63b3993127c171a6a536f001492

After enabling assert()s correctly, vm.c assert()s seem to fail. Need time to take a look into those. Will get to it eventually. For now, moving on without fixing this at all.

**Comment by gparmer** [comment]
Composite doesn't start with this: because vm.c asserts need to be re-looked.

Execution results:

phani@phani-thinkpad:~/transfer$ ./qemu.sh micro_boot.sh 
vm.c:kern_paging_map_init:135 - Assertion 'j != KERN_INIT_PGD_IDX || (boot_comp_pgd[j] | PGTBL_GLOBAL) == (i | PGTBL_PRESENT | PGTBL_WRITABLE | PGTBL_SUPER | PGTBL_GLOBAL)' failed
Shutting down...

**Comment by Others** [comment]
@phanikishoreg This is resolved, right?

**Comment by phanikishoreg** [comment]
yes. Commit #598d6b9c25a7a4687623fc26e3cca4ad4db58369 fixes this.
